# IUM FILM DATA CLEANING AND EDA
 placeholder

## Imports and Data

#### Importing Libraries

In [254]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 150)

#### Importing data

In [255]:
path = "C:/UNI/IUM/data"

In [256]:
try:
    df_movies = pd.read_csv(path + "/main_data/movies.csv")
    df_actors = pd.read_csv(path + "/main_data/actors.csv")
    df_countries = pd.read_csv(path + "/main_data/countries.csv")
    df_crew = pd.read_csv(path + "/main_data/crew.csv")
    df_genres = pd.read_csv(path + "/main_data/genres.csv")
    df_languages = pd.read_csv(path + "/main_data/languages.csv")
    df_posters = pd.read_csv(path + "/main_data/posters.csv")
    df_releases = pd.read_csv(path + "/main_data/releases.csv")
    df_studios = pd.read_csv(path + "/main_data/studios.csv")
    df_themes = pd.read_csv(path + "/main_data/themes.csv")

    df_tomatoes = pd.read_csv(path + "/additional_data/rotten_tomatoes_reviews.csv")
    df_oscar = pd.read_csv(path + "/additional_data/the_oscar_awards.csv")
except Exception as e:
    print(e)

## Data cleaning: main data

#### Movies

In [257]:
df_movies.rename(columns={'id': 'id_film'}, inplace=True)
df_movies.shape

(941597, 7)

In [258]:
df_movies.dtypes

id_film          int64
name            object
date           float64
tagline         object
description     object
minute         float64
rating         float64
dtype: object

In [259]:
df_movies.head()

,id_film,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09

In [260]:
df_movies.loc[df_movies.duplicated(subset=["name","date","description","minute"])]

,id_film,name,date,tagline,description,minute,rating
73818,1073819,Better Than Sex,2000.0,3 days in the life of a 1 night stand.,After a one-night stand a couple is faced with...,84.0,3.24
73819,1073820,Amoklauf,1994.0,NaN,A nameless waiter spends his days sitting arou...,65.0,NaN
73821,1073822,Still Working 9 to 5,2022.0,NaN,Examines the 40-year evolution of gender inequ...,95.0,NaN
73822,1073823,Power On: The Story of Xbox,2021.0,Four gamers. One idea. And a billion dollar bet.,Xbox almost didn't happen. Find out why in thi...,NaN,3.61
73823,1073824,Crossing the Line,2006.0,NaN,"In 1962, a U.S. soldier sent to guard the peac...",94.0,3.44
...,...,...,...,...,...,...,...
940447,1940448,Riina - Le verità nascoste,2018.0,NaN,NaN,45.0,NaN
940455,1940456,Yen Ching 燕京,2018.0,NaN,An intergenerational dilemma between immigrant...,64.0,NaN
940492,1940493,Our Cinema Oscar Special LIVE,2017.0,NaN,Gregg Turkington and Mark Proksch continue the...,107.0,NaN
940592,1940593,Happy Birthday!,2013.0,NaN,'Misery' doesn't like 'company' -- but 'compan...,20.0,NaN
941149,1941150,Extraños,NaN,NaN,NaN,NaN,NaN

In [261]:
df_movies.query('name == "River of No Return"')

,id_film,name,date,tagline,description,minute,rating
11418,1011419,River of No Return,1954.0,"Reckless, Roaring, Adventure of the Great Nort...",An itinerant farmer and his young son help a h...,91.0,3.18
403895,1403896,River of No Return,NaN,"The story of Frances Daingangan, one of the st...",Frances Daingangan is a 45-year old mother of ...,52.0,NaN
545141,1545142,River of No Return,2012.0,NaN,River of No Return Wilderness is the largest c...,53.0,NaN

In [262]:
df_movies.isna().sum()

id_film             0
name               10
date            91913
tagline        802210
description    160812
minute         181570
rating         850598
dtype: int64

In [263]:
df_movies.duplicated(subset=["name","date","minute"]).sum()

np.int64(6038)

In [264]:
df_movies = df_movies.groupby(['name', 'date', 'minute'], as_index=False).first()

In [265]:
df_movies.dropna(subset=["name", "description"], how='all', inplace=True)

In [266]:
df_movies.isna().sum()

name                0
date                0
minute              0
id_film             0
tagline        585720
description     56873
rating         618383
dtype: int64

#### Actors

In [267]:
df_actors.shape

(5798450, 3)

In [268]:
df_actors.dtypes

id       int64
name    object
role    object
dtype: object

In [269]:
df_actors.rename(columns={'id': 'id_film'}, inplace=True)

In [270]:
df_actors.dtypes

id_film     int64
name       object
role       object
dtype: object

In [271]:
df_actors.head()

   id_film               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [272]:
df_actors.fillna({"role":"Extra"})

         id_film               name                 role
0        1000001      Margot Robbie               Barbie
1        1000001       Ryan Gosling                  Ken
2        1000001    America Ferrera               Gloria
3        1000001  Ariana Greenblatt                Sasha
4        1000001           Issa Rae               Barbie
...          ...                ...                  ...
5798445  1941596            Marc Ma            Ba Cai/巴莱
5798446  1941596                线雨轩              Tata/塔塔
5798447  1941596       Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
5798448  1941597     Hiroshi Mikami                Extra
5798449  1941597      Keiko Oginome                Extra

[5798450 rows x 3 columns]

In [273]:
df_actors.duplicated().sum()

np.int64(946)

In [274]:
df_actors.drop_duplicates(inplace=True)

In [275]:
df_actors.shape

(5797504, 3)

#### Crew

In [276]:
df_crew.shape

(4720183, 3)

In [277]:
df_crew.dtypes

id       int64
role    object
name    object
dtype: object

In [278]:
df_crew.rename(columns={'id': 'id_film'}, inplace=True)

In [279]:
df_crew.head()

   id_film      role            name
0  1000001  Director    Greta Gerwig
1  1000001  Producer    Tom Ackerley
2  1000001  Producer   Margot Robbie
3  1000001  Producer  Robbie Brenner
4  1000001  Producer    David Heyman

In [280]:
df_crew.isna().sum()

id_film    0
role       0
name       1
dtype: int64

In [281]:
df_crew.fillna({"name":"unknown"},inplace=True)

In [282]:
df_crew.loc[df_crew.duplicated()]

         id_film                role                 name
1721     1000018              Stunts           Chris Webb
2691     1000031              Stunts          Sarah Irwin
2692     1000031              Stunts          Sarah Irwin
3920     1000043      Set decoration         Chris Arnold
6655     1000074             Casting        Magui Jimenez
...          ...                 ...                  ...
4716242  1940117               Sound         Greg Francis
4716243  1940117               Sound         Greg Francis
4718342  1940904  Assistant director       Choe Yeong-sik
4719628  1941357  Executive producer            Josh Earl
4720109  1941521               Sound  Oscar van Hoogevest

[1282 rows x 3 columns]

In [283]:
df_crew.drop_duplicates(inplace=True)

In [284]:
df_crew.duplicated().sum()

np.int64(0)

#### Geners

In [285]:
df_genres.shape

(1046849, 2)

In [286]:
df_genres.dtypes

id        int64
genre    object
dtype: object

In [287]:
df_genres.rename(columns={'id': 'id_film'}, inplace=True)

In [288]:
df_genres.head()

   id_film      genre
0  1000001     Comedy
1  1000001  Adventure
2  1000002     Comedy
3  1000002   Thriller
4  1000002      Drama

In [289]:
df_genres.isna().sum()

id_film    0
genre      0
dtype: int64

In [290]:
df_genres.duplicated().sum()

np.int64(0)

In [291]:
df_genres["genre"].unique()

array(['Comedy', 'Adventure', 'Thriller', 'Drama', 'Science Fiction',
       'Action', 'Music', 'Romance', 'History', 'Crime', 'Animation',
       'Mystery', 'Horror', 'Family', 'Fantasy', 'War', 'Western',
       'TV Movie', 'Documentary'], dtype=object)

####    Languages

In [292]:
df_languages.shape

(1038762, 3)

In [293]:
df_languages.dtypes

id           int64
type        object
language    object
dtype: object

In [294]:
df_languages.rename(columns={'id': 'id_film'}, inplace=True)

In [295]:
df_languages.head(10)

   id_film              type   language
0  1000001          Language    English
1  1000002  Primary language     Korean
2  1000002   Spoken language    English
3  1000002   Spoken language     German
4  1000002   Spoken language     Korean
5  1000003  Primary language    English
6  1000003   Spoken language  Cantonese
7  1000003   Spoken language    Chinese
8  1000003   Spoken language    English
9  1000004          Language    English

In [296]:
df_languages.isna().sum()

id_film     0
type        0
language    0
dtype: int64

In [297]:
df_languages.duplicated().sum()

np.int64(0)

In [298]:
np.sort(df_languages['language'].unique())

array(['Abkhaz', 'Afar', 'Afrikaans', 'Akan', 'Albanian', 'Amharic',
       'Arabic', 'Aragonese', 'Armenian', 'Assamese', 'Avaric', 'Avestan',
       'Aymara', 'Azerbaijani', 'Bambara', 'Bashkir', 'Basque',
       'Belarusian', 'Bengali, Bangla', 'Bislama', 'Bosnian', 'Breton',
       'Bulgarian', 'Burmese', 'Cantonese', 'Catalan', 'Chamorro',
       'Chechen', 'Chichewa, Chewa, Nyanja', 'Chinese', 'Chuvash',
       'Cornish', 'Corsican', 'Cree', 'Croatian', 'Czech', 'Danish',
       'Divehi, Dhivehi, Maldivian', 'Dutch', 'Dzongkha',
       'Eastern Punjabi, Eastern Panjabi', 'English', 'Esperanto',
       'Estonian', 'Ewe', 'Faroese', 'Fijian', 'Finnish', 'French',
       'Fula, Fulah, Pulaar, Pular', 'Galician', 'Ganda', 'Georgian',
       'German', 'Gibberish', 'Greek\xa0(modern)', 'Guaraní', 'Gujarati',
       'Haitian, Haitian Creole', 'Hausa', 'Hebrew\xa0(modern)', 'Herero',
       'Hindi', 'Hiri Motu', 'Hungarian', 'Icelandic', 'Ido', 'Igbo',
       'Indonesian', 'Interlingua', 'Interlingue', 'Inuktitut', 'Inupiaq',
       'Irish', 'Italian', 'Japanese', 'Javanese',
       'Kalaallisut, Greenlandic', 'Kannada', 'Kashmiri', 'Kazakh',
       'Khmer', 'Kikuyu, Gikuyu', 'Kinyarwanda', 'Kirundi', 'Komi',
       'Kongo', 'Korean', 'Kurdish', 'Kwanyama, Kuanyama', 'Kyrgyz',
       'Lao', 'Latin', 'Latvian', 'Limburgish, Limburgan, Limburger',
       'Lingala', 'Lithuanian', 'Luba-Katanga',
       'Luxembourgish, Letzeburgesch', 'Macedonian', 'Maithili',
       'Malagasy', 'Malay', 'Malayalam', 'Maltese', 'Manx', 'Marathi',
       'Mari', 'Marshallese', 'Mayan', 'Moldavian', 'Mongolian', 'Māori',
       'Nauruan', 'Navajo, Navaho', 'Ndonga', 'Nepali',
       'No spoken language', 'Northern Ndebele', 'Northern Sami',
       'Norwegian', 'Norwegian Bokmål', 'Norwegian Nynorsk', 'Nuosu',
       'Occitan', 'Ojibwe, Ojibwa',
       'Old Church Slavonic,\xa0Church Slavonic,\xa0Old Bulgarian',
       'Oriya', 'Oromo', 'Ossetian, Ossetic', 'Pashto, Pushto',
       'Persian\xa0(Farsi)', 'Polish', 'Portuguese', 'Pāli', 'Quechua',
       'Romanian', 'Romansh', 'Russian', 'Samoan', 'Sango',
       'Sanskrit (Saṁskṛta)', 'Sardinian', 'Scottish Gaelic, Gaelic',
       'Serbian', 'Serbo-Croatian', 'Shona', 'Sindhi',
       'Sinhalese, Sinhala', 'Slovak', 'Slovene', 'Somali',
       'Southern Ndebele', 'Southern Sotho', 'Spanish', 'Sundanese',
       'Swahili', 'Swati', 'Swedish', 'Tagalog', 'Tahitian', 'Tajik',
       'Tamil', 'Tatar', 'Telugu', 'Thai',
       'Tibetan Standard, Tibetan, Central', 'Tigrinya', 'Tola',
       'Tonga\xa0(Tonga Islands)', 'Tsonga', 'Tswana', 'Turkish',
       'Turkmen', 'Twi', 'Ukrainian', 'Urdu', 'Uyghur', 'Uzbek', 'Venda',
       'Vietnamese', 'Volapük', 'Walloon', 'Welsh', 'Western Frisian',
       'Wolof', 'Xhosa', 'Yiddish', 'Yolngu matha', 'Yoruba',
       'Zhuang, Chuang', 'Zulu'], dtype=object)

In [299]:
df_languages['language'] = df_languages['language'].astype(str).str.replace(r'\xa0', ' ', regex=True)
df_languages['language'] = df_languages['language'].str.split(',').str[0]
np.sort(df_languages['language'].unique())

array(['Abkhaz', 'Afar', 'Afrikaans', 'Akan', 'Albanian', 'Amharic',
       'Arabic', 'Aragonese', 'Armenian', 'Assamese', 'Avaric', 'Avestan',
       'Aymara', 'Azerbaijani', 'Bambara', 'Bashkir', 'Basque',
       'Belarusian', 'Bengali', 'Bislama', 'Bosnian', 'Breton',
       'Bulgarian', 'Burmese', 'Cantonese', 'Catalan', 'Chamorro',
       'Chechen', 'Chichewa', 'Chinese', 'Chuvash', 'Cornish', 'Corsican',
       'Cree', 'Croatian', 'Czech', 'Danish', 'Divehi', 'Dutch',
       'Dzongkha', 'Eastern Punjabi', 'English', 'Esperanto', 'Estonian',
       'Ewe', 'Faroese', 'Fijian', 'Finnish', 'French', 'Fula',
       'Galician', 'Ganda', 'Georgian', 'German', 'Gibberish',
       'Greek (modern)', 'Guaraní', 'Gujarati', 'Haitian', 'Hausa',
       'Hebrew (modern)', 'Herero', 'Hindi', 'Hiri Motu', 'Hungarian',
       'Icelandic', 'Ido', 'Igbo', 'Indonesian', 'Interlingua',
       'Interlingue', 'Inuktitut', 'Inupiaq', 'Irish', 'Italian',
       'Japanese', 'Javanese', 'Kalaallisut', 'Kannada', 'Kashmiri',
       'Kazakh', 'Khmer', 'Kikuyu', 'Kinyarwanda', 'Kirundi', 'Komi',
       'Kongo', 'Korean', 'Kurdish', 'Kwanyama', 'Kyrgyz', 'Lao', 'Latin',
       'Latvian', 'Limburgish', 'Lingala', 'Lithuanian', 'Luba-Katanga',
       'Luxembourgish', 'Macedonian', 'Maithili', 'Malagasy', 'Malay',
       'Malayalam', 'Maltese', 'Manx', 'Marathi', 'Mari', 'Marshallese',
       'Mayan', 'Moldavian', 'Mongolian', 'Māori', 'Nauruan', 'Navajo',
       'Ndonga', 'Nepali', 'No spoken language', 'Northern Ndebele',
       'Northern Sami', 'Norwegian', 'Norwegian Bokmål',
       'Norwegian Nynorsk', 'Nuosu', 'Occitan', 'Ojibwe',
       'Old Church Slavonic', 'Oriya', 'Oromo', 'Ossetian', 'Pashto',
       'Persian (Farsi)', 'Polish', 'Portuguese', 'Pāli', 'Quechua',
       'Romanian', 'Romansh', 'Russian', 'Samoan', 'Sango',
       'Sanskrit (Saṁskṛta)', 'Sardinian', 'Scottish Gaelic', 'Serbian',
       'Serbo-Croatian', 'Shona', 'Sindhi', 'Sinhalese', 'Slovak',
       'Slovene', 'Somali', 'Southern Ndebele', 'Southern Sotho',
       'Spanish', 'Sundanese', 'Swahili', 'Swati', 'Swedish', 'Tagalog',
       'Tahitian', 'Tajik', 'Tamil', 'Tatar', 'Telugu', 'Thai',
       'Tibetan Standard', 'Tigrinya', 'Tola', 'Tonga (Tonga Islands)',
       'Tsonga', 'Tswana', 'Turkish', 'Turkmen', 'Twi', 'Ukrainian',
       'Urdu', 'Uyghur', 'Uzbek', 'Venda', 'Vietnamese', 'Volapük',
       'Walloon', 'Welsh', 'Western Frisian', 'Wolof', 'Xhosa', 'Yiddish',
       'Yolngu matha', 'Yoruba', 'Zhuang', 'Zulu'], dtype=object)

#### Countries

In [300]:
df_countries.shape

(693476, 2)

In [301]:
df_countries.dtypes

id          int64
country    object
dtype: object

In [302]:
df_countries.rename(columns={'id': 'id_film'}, inplace=True)

In [303]:
df_countries.head()

   id_film      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany

In [304]:
df_countries.isna().sum()

id_film    0
country    0
dtype: int64

In [305]:
df_countries.duplicated().sum()

np.int64(0)

In [306]:
df_countries.duplicated().sum()

np.int64(0)

#### Posters

In [307]:
df_posters.shape

(941597, 2)

In [308]:
df_posters.dtypes

id       int64
link    object
dtype: object

In [309]:
df_posters.rename(columns={'id': 'id_film'}, inplace=True)

In [310]:
df_posters.head()

   id_film                                               link
0  1000001  https://a.ltrbxd.com/resized/film-poster/2/7/7...
1  1000002  https://a.ltrbxd.com/resized/film-poster/4/2/6...
2  1000003  https://a.ltrbxd.com/resized/film-poster/4/7/4...
3  1000004  https://a.ltrbxd.com/resized/film-poster/5/1/5...
4  1000005  https://a.ltrbxd.com/resized/film-poster/2/4/0...

In [311]:
df_posters.isna().sum()

id_film         0
link       180712
dtype: int64

In [312]:
df_posters[df_posters['link'].isnull()]

        id_film link
14018   1014019  NaN
15380   1015381  NaN
16467   1016468  NaN
18452   1018453  NaN
27193   1027194  NaN
...         ...  ...
941589  1941590  NaN
941590  1941591  NaN
941592  1941593  NaN
941593  1941594  NaN
941596  1941597  NaN

[180712 rows x 2 columns]

In [313]:
df_posters['link'] = df_posters['link'].fillna("no_link")

In [314]:
df_posters.duplicated().sum()

np.int64(0)

#### Releases

In [315]:
df_releases.shape

(1332782, 5)

In [316]:
df_releases.dtypes

id          int64
country    object
date       object
type       object
rating     object
dtype: object

In [317]:
df_releases.rename(columns={'id': 'id_film'}, inplace=True)

In [318]:
df_releases.head()

   id_film    country        date        type rating
0  1000001    Andorra  2023-07-21  Theatrical    NaN
1  1000001  Argentina  2023-07-20  Theatrical    ATP
2  1000001  Australia  2023-07-19  Theatrical     PG
3  1000001  Australia  2023-10-01     Digital     PG
4  1000001    Austria  2023-07-20  Theatrical    NaN

In [319]:
df_releases.isna().sum()

id_film         0
country         0
date            0
type            0
rating     998802
dtype: int64

In [320]:
df_releases['rating'].unique()

array([nan, 'ATP', 'PG', '12', 'U', '7', 'K-7', 'TP', '6', 'IIA', 'UA',
       '12A', 'T', 'G', 'N-13', 'B', '9', 'M/12', 'PG-13', '15', 'PG13',
       '13', 'A', '16', 'K-16', 'IIB', 'VM14', 'PG12', 'N-16', 'B-15',
       'M/14', 'M18', '14', 'R', 'C18', 'K15', '18', '11', '18A', 'K-18',
       '18PL', 'C', 'R-18', 'M/18', 'M', 'L', 'S', '0', 'AL', '14A',
       'K-12', 'K12', '15A', 'R-16', '10', 'AG', 'D', 'A-18', 'R16',
       'NC16', 'P', '18TC', 'III', 'VM18', 'M/16', 'R21', 'N-7', 'M/6',
       'AP', '8', 'R13', 'P13', 'R-13', 'C16', 'R18', '20', 'NR', 'K-13',
       'X', 'K18', 'N-18', '19', 'K', 'SU', '10A', 'APTA', 'R-15', 'APT',
       'KT/EA', 'K-15', 'I', 'ALL', 'C13', '18PA', 'RP13', 'Y7', 'NC-16',
       'KN', 'PG-15', 'K-11', 'K-8', 'PG-12', '18SG', 'EA', 'V', 'R-12',
       'K-17', 'B15', 'AA', '12PG', 'K-10', 'AP-12', 'TE', 'R12', '7-9PG',
       '13A', 'M/3', '21', '28', '2', '27', 'N-15', 'KT', 'SR', 'K-6-4',
       'NC-15', 'M/4', 'K-14', 'NC-17', 'MS12', 'GP', 'ZA', '15PG', 'R15',
       'E', 'RP16', 'M/16Q', '17', 'II', 'RC', 'K-3', '6A', 'PERE', 'MP',
       '7A', 'N16', 'K7', 'TV-MA', 'S-3', 'M16', 'UR', 'M12', 'PT',
       'IM-18', 'M13', 'UFD', 'IB', 'OM', 'F', 'M6', 'IT', 'TV-14',
       'TV-PG', '16E', 'KNT', 'ENA', '16LS', '18X', '12E', 'BIFFF', 'ITA',
       'CAT3', 'AM18', 'BTL', 'PM13', 'MX-A', '15-A', 'USA', 'M21', 'M4',
       'FSK12', 'LH', 'PG0', 'PG-14', 'MA', 'M-18', 'JP', 'IMDB', 'U/A',
       'TV-Y7', 'NYFF', 'FSK16', 'PG15', 'TV-G', 'PM16', '13-A', 'B-12',
       'USA-R', 'MPAA', 'P15', 'AP16', 'MA15+', 'R18+', 'R15+', 'SAM18',
       'TODOS', 'M14', 'TT', '18SX', 'HD', 'SAM13', 'TR', 'TW', 'DVD',
       'PGL', 'NR-12', 'VN', 'MG6', 'YES', 'FAJR', 'UN', 'K+', 'KK', 'PC',
       'EM', 'VM-14', 'TV-13', 'IM16', 'PG-17', 'PD-14', '5', 'NC18',
       'PG-16', 'PM18', 'QA', '13V', 'P-13', 'AKA', 'PG10', 'APTO', 'N/C',
       'PM14', 'TVMA', '13PL', 'FIC', 'MA-13', '4', 'PG16', '16LV', 'NN',
       'N', 'II-B', '16SL', '05', 'PG18', 'K11', '13L', 'FSK-0', 'R-15+',
       'MA+', 'FSK6', 'SAM15', 'IM14', 'R13+', '352', '16LPV', 'KG', '1',
       'TV', '16L', 'IM18', 'SAM16', 'NC15', 'FSK', '13VL', '3', 'TV14',
       'FSK0', 'OK', 'BE/12', 'INCAA', 'GA', '123', 'BR', 'FPBA'],
      dtype=object)

In [321]:
rating_map = {
    'ATP': 0, 'U': 0, 'G': 0, 'AL': 0, 'AG': 0, 'P': 0, 'AP': 0, 'NR': 0,
    'K': 0, 'SU': 0, 'APTA': 0, 'APT': 0, 'KT/EA': 0, 'ALL': 0, 'KN': 0,
    'EA': 0, 'KT': 0, 'GP': 0, 'ZA': 0, 'E': 0, 'PERE': 0, 'MP': 0,

    'M/3': 3, 'K-3': 3,
    'M/4': 4,
    'M/6': 6, 'K-6-4': 6, '6A': 6,
    'K-7': 7, 'N-7': 7, 'Y7': 7, '7A': 7, 'K7': 7,
    'K-8': 8,
    '7-9PG': 9,

    'PG': 10, 'TP': 10, '10A': 10, 'K-10': 10,
    'K-11': 11,

    'IIA': 12, 'UA': 12, '12A': 12, 'B': 12, 'M/12': 12, 'PG12': 12,
    'K-12': 12, 'K12': 12, 'PG-12': 12, 'R-12': 12, '12PG': 12, 'AP-12': 12,
    'R12': 12, 'MS12': 12, 'II': 12,

    'T': 13, 'N-13': 13, 'PG-13': 13, 'PG13': 13, 'R13': 13, 'P13': 13,
    'R-13': 13, 'K-13': 13, 'C13': 13, 'RP13': 13, 'TE': 13, '13A': 13,

    'VM14': 14, 'M/14': 14, '14A': 14, 'K-14': 14,

    'IIB': 15, 'B-15': 15, 'K15': 15, '15A': 15, 'R-15': 15, 'K-15': 15,
    'PG-15': 15, 'B15': 15, 'N-15': 15, 'NC-15': 15, '15PG': 15, 'R15': 15,

    'K-16': 16, 'N-16': 16, 'R-16': 16, 'R16': 16, 'NC16': 16, 'M/16': 16,
    'C16': 16, 'NC-16': 16, 'RP16': 16, 'M/16Q': 16, 'N16': 16,

    'R': 17, 'M': 17, 'K-17': 17, 'NC-17': 17,

    'A': 18, 'M18': 18, 'C18': 18, '18A': 18, 'K-18': 18, '18PL': 18,
    'C': 18, 'R-18': 18, 'M/18': 18, 'L': 18, 'S': 18, 'D': 18, 'A-18': 18,
    '18TC': 18, 'III': 18, 'VM18': 18, 'R18': 18, 'X': 18, 'K18': 18,
    'N-18': 18, 'I': 18, '18PA': 18, '18SG': 18, 'V': 18, 'AA': 18,
    'SR': 18, 'RC': 18, 'TV-MA': 18,

    'R21': 21
}

df_releases['age_min'] = df_releases['rating'].map(rating_map)

df_releases['age_min']=df_releases['age_min'].fillna(0)
df_releases['age_min'] = df_releases['age_min'].astype('Int64')

df_releases.pop('rating')
df_releases

         id_film    country        date        type  age_min
0        1000001    Andorra  2023-07-21  Theatrical        0
1        1000001  Argentina  2023-07-20  Theatrical        0
2        1000001  Australia  2023-07-19  Theatrical       10
3        1000001  Australia  2023-10-01     Digital       10
4        1000001    Austria  2023-07-20  Theatrical        0
...          ...        ...         ...         ...      ...
1332777  1940967        USA  1909-01-01  Theatrical        0
1332778  1940968     Sweden  1908-11-11  Theatrical        0
1332779  1940969     France  1902-01-01  Theatrical        0
1332780  1940970     France  1902-01-01  Theatrical        0
1332781  1940971     France  1902-01-01  Theatrical        0

[1332782 rows x 5 columns]

In [322]:
df_releases.isna().sum()

id_film    0
country    0
date       0
type       0
age_min    0
dtype: int64

In [323]:
df_releases.duplicated().sum()

np.int64(0)

#### Studios

In [324]:
df_studios.shape

(679283, 2)

In [325]:
df_studios.dtypes

id         int64
studio    object
dtype: object

In [326]:
df_studios.rename(columns={'id': 'id_film'}, inplace=True)

In [327]:
df_studios.head()

   id_film                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
3  1000001                   Mattel
4  1000001    Warner Bros. Pictures

In [328]:
df_studios.isna().sum()

id_film     0
studio     10
dtype: int64

In [329]:
df_studios.fillna('Unknown', inplace=True)

In [330]:
df_studios.duplicated().sum()

np.int64(212)

In [331]:
df_studios.drop_duplicates()

        id_film                   studio
0       1000001  LuckyChap Entertainment
1       1000001             Heyday Films
2       1000001           NB/GG Pictures
3       1000001                   Mattel
4       1000001    Warner Bros. Pictures
...         ...                      ...
679278  1941596               上海猫眼影业有限公司
679279  1941596            坏小子（北京）传媒有限公司
679280  1941596         亚太国影（重庆）文化传媒有限公司
679281  1941596               凤凰传奇影业有限公司
679282  1941596             无双（深圳）影业有限公司

[679071 rows x 2 columns]

#### Themes

In [332]:
df_themes.shape

(125641, 2)

In [333]:
df_themes.dtypes

id        int64
theme    object
dtype: object

In [334]:
df_themes.rename(columns={'id': 'id_film'}, inplace=True)

In [335]:
df_themes.head()

   id_film                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...

In [336]:
df_themes.isna().sum()

id_film    0
theme      0
dtype: int64

In [337]:
df_themes.duplicated().sum()

np.int64(0)

In [338]:
df_themes["theme"].unique()

array(['Humanity and the world around us', 'Crude humor and satire',
       'Moving relationship stories',
       'Emotional and captivating fantasy storytelling',
       'Surreal and thought-provoking visions of life and death',
       'Quirky and endearing relationships',
       'Amusing jokes and witty satire',
       'Laugh-out-loud relationship entanglements',
       'Intense violence and sexual transgression',
       'Twisted dark psychological thriller',
       'Heartbreaking and moving family drama',
       'Enduring stories of family and marital drama',
       'Touching and sentimental family stories',
       'Intense political and terrorist thrillers',
       'Powerful stories of heartbreak and suffering',
       'Dreamlike, quirky, and surreal storytelling',
       'Challenging or sexual themes & twists',
       'Graphic violence and brutal revenge', 'Song and dance',
       'Dazzling vocal performances and musicals',
       'Captivating relationships and charming romance',
       'Dance rhythms and catchy tunes',
       'Emotional life of renowned artists',
       'Charming romances and delightful chemistry',
       'Politics and human rights', 'Epic history and literature',
       'Riveting political and presidential drama',
       'Dangerous technology and the apocalypse',
       'Political drama, patriotism, and war',
       'Monsters, aliens, sci-fi and the apocalypse',
       'Imaginative space odysseys and alien encounters',
       'Action-packed space and alien sagas',
       'Thought-provoking sci-fi action and future technology',
       "Humanity's odyssey: earth and beyond",
       'Crime, drugs and gangsters', 'Gripping, intense violent crime',
       'Epic heroes',
       'Superheroes in action-packed battles with villains',
       'Gritty crime and ruthless gangsters',
       'Violent action, guns, and crime', 'Heists and thrilling action',
       'Brutal, violent prison drama', "Kids' animated fun and adventure",
       'Action comedy and silly heroics',
       'Teen school antics and laughter',
       'Student coming-of-age challenges', 'High speed and special ops',
       'Thrillers and murder mysteries',
       'Explosive and action-packed heroes vs. villains',
       'Noir and dark crime dramas',
       'Intriguing and suspenseful murder mysteries',
       'Horror, the undead and monster classics',
       'Terrifying, haunted, and supernatural horror',
       'Creepy, chilling, and terrifying horror',
       'Gory, gruesome, and slasher horror',
       'Racism and the powerful fight for justice',
       'Suspenseful crime thrillers', 'Gothic and eerie haunting horror',
       'Erotic relationships and desire', 'Underdogs and coming of age',
       'Emotional and touching family dramas',
       'Emotional teen coming-of-age stories', 'Relationship comedy',
       'Gags, jokes, and slapstick humor', 'Funny jokes and crude humor',
       'Engaging, intense crime and casino drama',
       'Violent crime and drugs',
       'Fantasy adventure, heroism, and swordplay',
       'Historical battles and epic heroism',
       'Fairy-tale fantasy and enchanted magic',
       'Adorable animals and heartwarming families',
       'Fascinating, emotional stories and documentaries',
       'War and historical adventure', 'Nazis and World War II',
       'Military combat and heroic soldiers', 'Bravery in War',
       'Adrenaline-fueled action and fast cars',
       'Intense combat and martial arts', 'Westerns',
       'Wild west outlaws and gunfights',
       'Western frontier dramas with a touch of humor',
       'Emotional LGBTQ relationships', 'Passion and romance',
       'Holiday joy and heartwarming Christmas',
       'Catchy songs and hilarious musical comedy',
       'Sci-fi horror, creatures, and aliens', 'Faith and religion',
       'Epic adventure and breathtaking battles',
       'Tragic sadness and captivating beauty',
       'Disastrous voyages and heroic survival',
       'Underdog fighting and boxing stories',
       'Air pilot heroism and survival',
       'Exciting spy thrillers with tense intrigue',
       'Sci-fi monster and dinosaur adventures',
       'Chilling experiments and classic monster horror',
       'Captivating vision and Shakespearean drama',
       'Powerful poetic and passionate drama', 'Spooky, scary comedy',
       'Legendary musicians and stardom',
       'Religious faith, sin, and forgiveness', 'Bloody vampire horror',
       'Inspiring sports underdog stories',
       'Survival horror and zombie carnage',
       'Extreme gory horror and cannibalism',
       'Lavish dramas and sumptuous royalty',
       'Faith and spiritual journeys',
       'Politics, propaganda, and political documentaries',
       'Teen friendship and coming-of-age', 'Bollywood emotional dramas'],
      dtype=object)

## Data Cleaning: Additional

### Reviews

In [339]:
df_tomatoes.shape

(1129887, 9)

In [340]:
df_tomatoes.dtypes

rotten_tomatoes_link    object
movie_title             object
critic_name             object
top_critic                bool
publisher_name          object
review_type             object
review_score            object
review_date             object
review_content          object
dtype: object

In [341]:
df_tomatoes.head()

,rotten_tomatoes_link,movie_title,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,m/0814255,Percy Jackson & the Olympians: The Lightning T...,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...
3,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
4,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...

In [342]:
df_tomatoes.isna().sum()

rotten_tomatoes_link         0
movie_title                  0
critic_name              18521
top_critic                   0
publisher_name               0
review_type                  0
review_score            305902
review_date                  0
review_content           65778
dtype: int64

In [343]:
df_tomatoes["review_date"]=pd.to_datetime(df_tomatoes["review_date"], format="%Y-%m-%d", errors="coerce")
df_tomatoes.dtypes

rotten_tomatoes_link            object
movie_title                     object
critic_name                     object
top_critic                        bool
publisher_name                  object
review_type                     object
review_score                    object
review_date             datetime64[ns]
review_content                  object
dtype: object

In [344]:
base_url = "https://www.rottentomatoes.com/"
df_tomatoes['rotten_tomatoes_link'] = base_url + df_tomatoes['rotten_tomatoes_link'].astype(str)
df_tomatoes.head()

,rotten_tomatoes_link,movie_title,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,https://www.rottentomatoes.com/m/0814255,Percy Jackson & the Olympians: The Lightning T...,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,https://www.rottentomatoes.com/m/0814255,Percy Jackson & the Olympians: The Lightning T...,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,https://www.rottentomatoes.com/m/0814255,Percy Jackson & the Olympians: The Lightning T...,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...
3,https://www.rottentomatoes.com/m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
4,https://www.rottentomatoes.com/m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...

#### Normalizing data: review scores

In [345]:
df_tomatoes['review_score'].unique()

array([nan, '3.5/5', '1/4', 'B', '3/5', '4/5', '2/4', '2/5', 'C', '2.5/4',
       '3/4', 'C-', '2.75/5', 'B-', '2.5/5', '5.5/10', '1/5', 'C+', 'D+',
       '1.5/4', '6.5/10', '3/10', '1.5/5', '4/10', '7/10', '6/10', 'B+',
       '5/5', 'A-', '4.5/5', '5.78/10', '3.5/4', 'A', '9/10', '8.5/10',
       '4/4', '83/100', '8/10', '92/100', '82/100', '84/100', '10/10',
       'D-', 'F', '0.5/4', 'D', '5/10', '2/10', '2/6', '0.5/5', '0/4',
       '0/5', '76/100', '87/100', '74/100', '86/100', '81/100', '56/100',
       '78/100', '2.25/5', '8.8/10', '0/10', '44/100', '2.75/4', '2.4/5',
       '8.6/10', '79/100', '68/100', '80/100', '90/100', '66/100',
       '91/100', '0.3/5', '9.2/10', '2.7/5', '57/100', '4/6', '3/6',
       '73/100', '42/100', '65/100', '7.5/10', '4.5/10', '5/6', '1/6',
       '70/100', '3.5/10', '71/100', '0.1/5', '3.25/10', '89/100',
       '40/100', '64/100', '62/100', '1/10', '3.75/5', '37/100', '49/100',
       '60/100', '3.3/5', '77/100', '5.25/10', '1.4/4', '75/100', '1.5/6',
       '85/100', '4.25/10', '47/100', '6/8', '52/100', '63/100', '50/100',
       '41/100', '46/100', '6.95/10', '53/100', '9.5/10', '59/100',
       '43/100', '9.45/10', '45/100', '69/100', '7.25/10', '5.85/10',
       '9.88/10', '39/100', '0.13/1', '8.25/10', '5.75/10', '6.1/10',
       '6.8/10', '8.9/10', '8.75/10', '2.5/10', '5.9/10', '4.2/10',
       '7.35/10', '4.6/10', '6.75/10', '4.90/10', '4.827/10', '2/2',
       '58/100', '4.75/10', '3.4/10', '88/100', '5.48/10', '9.16/10',
       '3.4/4', '4.25/5', '3.7/10', '6.765/10', '67/100', '34/100',
       '51/100', '3.4/5', '72/100', '93/100', '5', '95/95', '98/100',
       '94/100', '99/100', '4', '55/100', '61/100', '35/100', '95/100',
       '1/3', '5/8', '7', '4.2/5', '3', '30/100', '54/100', '48/100',
       '18/100', '10', '25/100', '7/5', '3.25/5', '7.4/10', '2', '6.2/10',
       '5.12/10', '5/100', '1', '0.75/5', '8', '100/100', '2.8/4',
       '2.25/4', '31/100', '2.4/4', '32/100', '3.8/5', '8.3/10', '8.4/10',
       '5.3/10', '0/100', '0.2/5', '8.7/10', '2.2/5', '2.3/5', '3.2/5',
       '2.8/5', '2.75/3', '4.85/10', '3.5/6', '3.25/4', '0.5/10',
       '1.75/4', '28/100', '9.25/10', '5.80/10', '6.25/10', '7.2/10',
       '6.9/10', '1.2/5', '8.35/10', '6.4/10', '7/11', '8.70/10',
       '9.75/10', '1.21/10', '1.35/5', '23/100', '38/100', '6.3/10',
       '8.85/10', '7.3/10', '7.15/10', '1.25/4', '3.9/10', '4.21/10',
       '9.35/10', '2.75/10', '8.76/10', '7.7/10', '7.75/10', '5.15/10',
       '7.85/10', '1.8/5', '0', '6.45/10', '5.95/10', '8.1/10', '3.7/5',
       '7.9/10', '9.9/10', '13/20', '6', '4.75/5', '2.83/5', '17/20',
       '8.74/10', '9', '7.8/10', '5.8311/10', '47/50', '3.20/10',
       '6.65/10', '5.88/10', '19/100', '2.5/3', '15/100', '8.621/10',
       '16/20', '1.75/5', '5.8/10', '1.5/10', '8.50/10', '5.65/10',
       '10.50/20', '9.19/10', '4.4/10', '5.6/10', '14.5/20', '4.1/5',
       '8.05/10', '0/6', '1.6/5', '3.1/5', '6.85/10', '4.35/10', '9.1/10',
       '8.88/10', '6.6/10', '6.7/10', '5.4/10', '20/20', '8.2/10',
       '16.5/20', '7.1/10', '5.7/10', '11/20', '8.95/10', '3.75/10',
       '15/20', '3.6/5', '7.6/10', '5.9737991/10', '18.5/20', '14/20',
       '7.05/10', '18/20', '9.86/10', '4.8/10', '4.7/10', '2.74/10',
       '4.9/10', '26/100', '2.12/5', '5.2/10', '7.96/10', '21/100',
       '6.9921/10', '4.5/4', '7.892/10', '5.5/5', '1/54', '1.2/10',
       '8.89/10', '33/100', '8.99/10', '5.5/20', '8.10/10', '6.68/10',
       '13/100', '2.9/10', '5.61/10', '4.65/10', '8/20', '9.12/10', '3/3',
       '5.49/10', '20/100', '6.78/10', '10/20', '0.02/5', '3.8/10',
       '8.65/10', '5.1/10', '9/5', '1.7/5', '25', '8.7328/10',
       '7.00122/10', '9.851/10', '8.251/10', '5/20', '7.57/10', '12/20',
       '2.1/5', '9.5/20', '10/100', '5.51/10', '1.4/5', '2.6/6', '9.4/10',
       '4.8/5', '4.45/10', '4.65/5', '2.6/5', '3.15/5', '6.98/10',
       '4.7/5', '4.1/10', '3.5/3', '4.4/5', '9.3/10', '4.3/5', '3.9/5',
       '2.20282652/10', '3.75/4', '3.3/10', '11.5/20', '7.5/20',
       '8.53899/10', '6/13', '2.11/5', '9.7/10', '2.6/10', '0.7221/10',
       '3.76/5', '2.95/10', '6.15/10', '7.5314585/10', '8.15/10',
       '9.85/10', '97/100', '7.83/10', '3.2121/10', '8.55/10',
       '2.282303/10', '88', '1.5/2', '4.21382343/10', '8/100', '17.5/20',
       '1.24/5', '1.25/5', '4.3/10', '2.7/10', '4.521/10', '6.0001/10',
       '4.143641/10', '9.15/10', '48', '4.05524/10', '8/5', '3/100',
       '3.83412437/10', '9.6/10', '9.79/10', '7.21/10', '9.5/5', '3.2/10',
       '7.696/10', '5.872/10', '9.50/20', '5.1921/10', '2.892521821/10',
       '0.81/1', '27/100', '6.35/10', '2.9/5', '9.74/10', '9.33/10',
       '7.02/10', '2.1/10', '7.89/10', '2.50/5', '9.21/10', '5.57/10',
       '19/20', '9.8/10', '8.32/10', '1/1', '5.9821/10', '8.385/10',
       '0.5/5.5', '45', '7.95/10', '6.09/10', '1.9/10', '3.55/10',
       '7.45/10', '7.62121/10', '1.9/5', '3.515/10', '15.5/20', '3.85/10',
       '8.72/10', '35/4', '5.5/6', '36/100', '9.1221/10', '9.65/10',
       '4.70/10', '2.2/10', '7.61/10', '2.3/4', '6.4821/10', '7.3821/10',
       '8.3721/10', '5.44/10', '8.92/10', '7.49/10', '8.225/10', '0.25/4',
       '1.5242228/10', '5.56/10', '9/20', '24/100', '7.01/10', '9.67/10',
       '7.2234238/10', '6.00024/10', '7.111113314/10', '8.21/10',
       '5.21/10', '79/80', '9.145/10', '9.865/10', '4.95/10', '5.6642/10',
       '9/100', '6.875/10', '0.66/10', '1.2/4', '5.8943/10', '3.99/10',
       '13.5/20', '61/00', '5.72/10', '1.3/5', '0.05/4', '4.6/5',
       '8.57/10', '24', '0/1000', '5.35/10', '29/100', '1.9528/10', '35',
       '7.65/10', '5.55/10', '2.5/20', '69/70', '9.26/10', '8.735/10',
       '6.1121/10', '6.0000001/10', '2/8', '9.78/10', '5.45/10',
       '14.50/20', '6.26/10', '2.85/5', '2.6/4', '7.218/10', '0.6/1',
       '3.021/10', '7.10/10', '0.96/10', '8.666/10', '3/40', '0.82/10',
       '7.98/10', '5.5542/10', '8.901/10', '2.55/5', '7.22/10', '5.70/10',
       'A  -', '7.04/10', '2.4/10', '5.89521/10', '2.8/10', '7.3856/10',
       '8.899327/10', '1.1/2', '8.2621/10', '7.212121/10', '4.89215/10',
       '9.89/10', '2.212521/10', '22/100', '5.6521/10', '8.87/10',
       '3.1/10', '4/5.5', '4.95/5', '8.19/10', '9.552/10', '7/20',
       '4.211/10', '4/3.5', '46', '4.9837/10', '9.38/10', '5.284849/10',
       '8.67/10', '6.9621/10', '2.5/50', '2.255/5', '90', '75', '8.61/10',
       '3.5/5.5', '5.81/10', '66/70', '3.222423/10', '4.2112/10',
       '1.82/10', '6.000003231/10', '3.76/10', '5.76/10', '2/54', '0.8/5',
       '6/11', '8.458/10', '2.89/5', '5.8921/10', '8.496/10', '2.3/10',
       '0.21/10', '4.51/10', '9.76/10', '59/60', '0.9/10', '3.65/5',
       '6/6', '6.7/8', '9.46/10', '8.45/10', '8.26/10', '1.85/10',
       '0.75/10', '4.89/10', '6.55/10', '1.62/5', '0.85/10', '9.121/10',
       '9.6421/10', '8.5788222/10', '3.45/5', '96/100', '67/10',
       '7.2621/10', '2/3', '5.23/10', '7.79/10', '9.1421/10', '87/10',
       '12.50/20', '7.825/10', '8.921/10', '6.24/10', '8.124/10',
       '8.01/10', '4.56/10', '1.5/3', '4.79/10', '8.16/10', '0.59/1',
       '2.7/4', '1.1/5', '89', '4.55/10', '2.5/6', '9.8521/10',
       '3.7822391/10', '7.2521/10', '7.18321/10', '3.6/4', 'C  -',
       '8.42/10', '9.73889/10', '12/100', '7.44/10', '8.5/5', '6/20',
       '6.01/10', '34', '8.98/10', '7.48/10', '3.65/10', '7.0921/10',
       '3.35/5', '1.4/10', '4/0', '6.96/10', '7.001/10', '5.22/10',
       '1.8/4', '16/100', '9.889/10', '14/100', '8.999/10', '9.188/10',
       '7.021/10', '4.42/10', '8.212121/10', '3.6/10', '0.7765823/10',
       '8.425/10', '9.48/10', '9.30/10', '4.86/10', '7.5211/10', '5/11',
       '8.71/10', '68', '3.7521/10', '4.021/10', '8.881/10', '5.10/10',
       '3/5.5', '95', '5.623433899/10', '0.65/10', '7/8', '9.18/10',
       '5.82/10', '5.212/10', '5.895/10', '6.8666/10', '920', '3.0782/10',
       '2.95/5', '4.22/10', '0.13/5', '2.65/10', '0.4/5', '8.453895/10',
       '6.001/10', '9.52/10', '6.16/10', '8.9521/10', '9.85621/10',
       '76/10', '0.664363/10', '9.51/10', '5.02120621/10', '3.2/4',
       '2/20', '5.1221/10', '12.5/20', '8.327/10', '1.88/10', '11/100',
       '75/10', '8.39421/10', '910', '9.95/10', '2/9', '8.199/10',
       '8.485/10', '7.621/10', '5.232121/10', '5.67/10', '8.24/10',
       '39/40', '3/5.4', '2/100', '7.94215/10', '9.68/10', '6/5',
       '6.19/10', '25/4', '4.5/6', '9.021/10', '8.32321/10', '7.87/10',
       '5.50/10', '8.2521/10', '2.1/2', '5.05/10', '0.6/10', '3.5/20',
       '9.14/10', '7.42/10', '9.2021/10', '6.05/10', '4/8', '3.54/5',
       '14', '9.49/10', '6.97/10', '4.9834326/10', '10/90', '72', '67',
       '45/5', '7.0155/10', '3.3/4', '6.89/10', '9.921/10', '80',
       '0.666/4', '2.55/4', '1.1/10', '3.5/18', '73/10', '8.30/10',
       '8.56/10', '6.8843/10', '6.00001/10', '4.364221/10', '4.293382/10',
       '6.84/10', '9.01/10', '8.68/10', '9.649821/10', '3/45',
       '8.692121/10', '70', '6.02/10', '0.58/1', '5.4221/10', '7.12/10',
       '8.1921/10', '9.87/10', '8.84/10', '9.20/10', '0.8/10',
       '8.9621/10', '3/20', '0.52/1', '8.3/100', '4/100', '1.75/10',
       '1.8/10', '4.0001/10', '77', '5.9999/10', '9.66/10', '9.99/10',
       '5.751/10', '7.55/10', '5.01/10', '3.56339/10', '4.558/10',
       '7.94/10', '3.5/44', '8.765/10', '4.35/5', '21/24', '6.02121/10',
       '1/2', '7.4921/10', '5.046/10', '9.56/10'], dtype=object)

In [346]:
df_tomatoes[~df_tomatoes['review_score'].str.contains('/', na=False)]['review_score'].unique()

array([nan, 'B', 'C', 'C-', 'B-', 'C+', 'D+', 'B+', 'A-', 'A', 'D-', 'F',
       'D', '5', '4', '7', '3', '10', '2', '1', '8', '0', '6', '9', '25',
       '88', '48', '45', '24', '35', 'A  -', '46', '90', '75', '89',
       'C  -', '34', '68', '95', '920', '910', '14', '72', '67', '80',
       '70', '77'], dtype=object)

In [347]:
letter_map = {
    'A+': 5.0, 'A': 5.0, 'A-': 4.5,
    'B+': 4.0, 'B': 3.5, 'B-': 3.0,
    'C+': 2.5, 'C': 2.0, 'C-': 1.5,
    'D+': 1.0, 'D': 1.0, 'D-': 0.5,
    'F': 0.0
}

df_tomatoes['review_score'] = df_tomatoes['review_score'].astype(str).str.strip().str.upper()
df_tomatoes['score'] = df_tomatoes['review_score'].map(letter_map)

fractions = df_tomatoes['review_score'].str.split('/', expand=True)
numerator = pd.to_numeric(fractions[0], errors='coerce')
denominator = pd.to_numeric(fractions[1], errors='coerce')
fraction_res = (numerator / denominator) * 5.0

df_tomatoes['score'] = df_tomatoes['score'].fillna(fraction_res)

df_tomatoes['score'] = df_tomatoes['score'].fillna(-1)
df_tomatoes[['review_score', 'score']]

        review_score  score
0                NAN   -1.0
1                NAN   -1.0
2                NAN   -1.0
3              3.5/5    3.5
4                NAN   -1.0
...              ...    ...
1129882          2/5    2.0
1129883        3.5/5    3.5
1129884           B+    4.0
1129885        3.5/5    3.5
1129886            C    2.0

[1129887 rows x 2 columns]

In [348]:
df_tomatoes.dtypes

rotten_tomatoes_link            object
movie_title                     object
critic_name                     object
top_critic                        bool
publisher_name                  object
review_type                     object
review_score                    object
review_date             datetime64[ns]
review_content                  object
score                          float64
dtype: object

In [349]:
df_tomatoes.drop(columns= ['review_score'])
df_tomatoes.duplicated(subset=["movie_title", "critic_name", "publisher_name", "review_type", "review_content", "review_date"]).sum()

np.int64(119574)

In [350]:
df_tomatoes = df_tomatoes.drop_duplicates(subset=["movie_title", "critic_name", "publisher_name", "review_type", "review_content", "review_date"],keep="first")
df_tomatoes.shape

(1010313, 10)

### Oscars

In [351]:
df_oscar.shape

(10889, 7)

In [352]:
df_oscar.dtypes

year_film         int64
year_ceremony     int64
ceremony          int64
category         object
name             object
film             object
winner             bool
dtype: object

In [353]:
df_oscar.head()

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False

In [354]:
df_oscar["year_film"]=pd.to_datetime(df_oscar["year_film"], format="%Y", errors="coerce")
df_oscar["year_ceremony"]=pd.to_datetime(df_oscar["year_ceremony"], format="%Y", errors="coerce")

In [355]:
df_oscar.dtypes

year_film        datetime64[ns]
year_ceremony    datetime64[ns]
ceremony                  int64
category                 object
name                     object
film                     object
winner                     bool
dtype: object

In [356]:
df_oscar.duplicated(subset=["year_film", "year_ceremony", "ceremony", "category", "name", "film"]).sum()

np.int64(11)

In [357]:
df_oscar = df_oscar.drop_duplicates(subset=["year_film", "year_ceremony", "ceremony", "category", "name", "film"],keep="first")

In [358]:
df_oscar.duplicated(subset=["year_film", "year_ceremony", "ceremony", "category", "name", "film"]).sum()

np.int64(0)

In [359]:
df_oscar.isna().sum()

year_film          0
year_ceremony      0
ceremony           0
category           0
name               4
film             318
winner             0
dtype: int64

In [360]:
df_oscar[df_oscar["name"].isna()]

,year_film,year_ceremony,ceremony,category,name,film,winner
10513,2020-01-01,2021-01-01,93,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10635,2021-01-01,2022-01-01,94,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10759,2022-01-01,2023-01-01,95,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10885,2023-01-01,2024-01-01,96,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True

In [361]:
df_oscar.dropna(subset=['name'], inplace=True)

## Saving Data

In [362]:
output_dir = "clean_datasets"
os.makedirs(output_dir, exist_ok=True)

df_actors.to_csv(os.path.join(output_dir, "df_actors.csv"), index=False)
df_countries.to_csv(os.path.join(output_dir, "df_countries.csv"), index=False)
df_crew.to_csv(os.path.join(output_dir, "df_crew.csv"), index=False)
df_movies.to_csv(os.path.join(output_dir, "df_movies.csv"), index=False)
df_languages.to_csv(os.path.join(output_dir, "df_languages.csv"), index=False)
df_posters.to_csv(os.path.join(output_dir, "df_posters.csv"), index=False)
df_releases.to_csv(os.path.join(output_dir, "df_releases.csv"), index=False)
df_themes.to_csv(os.path.join(output_dir, "df_themes.csv"), index=False)
df_genres.to_csv(os.path.join(output_dir, "df_genres.csv"), index=False)
df_studios.to_csv(os.path.join(output_dir, "df_studios.csv"), index=False)
df_tomatoes.to_csv(os.path.join(output_dir, "df_tomatoes.csv"), index=False)
df_oscar.to_csv(os.path.join(output_dir, "df_oscars.csv"), index=False)